---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "panopticon.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "panopticon.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ (split ":" .Values.agent.metricsBind)._1 | default "9090" | quote }}
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "panopticon.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ (split ":" .Values.agent.metricsBind)._1 | default 9090 }}
      targetPort: {{ (split ":" .Values.agent.metricsBind)._1 | default 9090 }}
      protocol: TCP
